// Generates workflow.md — a mermaid diagram of the rendered agent set.
// Each node is filled with its agent's `color:` from frontmatter (10-color palette)
// instead of an archetype-default. This matches the colors in <docs_root>/flows.md
// so multi-agent runs are visually consistent.
// Returns { written: [], skipped: [] } — always empty. The conflict handler is the
// single source of truth for what was written or skipped (stats are mutated there).

import { resolve, join } from 'node:path';

// Color palette — same hex values used by the flows.md template.
const COLOR_FILLS = {
  cyan:   { fill: '#2d6a7a', stroke: '#22d3ee' },
  blue:   { fill: '#2d4a7a', stroke: '#60a5fa' },
  red:    { fill: '#7a2d2d', stroke: '#f87171' },
  pink:   { fill: '#7a2d5b', stroke: '#f472b6' },
  purple: { fill: '#5b2d7a', stroke: '#c084fc' },
  yellow: { fill: '#7a6a2d', stroke: '#facc15' },
  green:  { fill: '#2d7a3a', stroke: '#4ade80' },
  teal:   { fill: '#2d7a6a', stroke: '#2dd4bf' },
  orange: { fill: '#e8922a', stroke: '#fb923c' },
  white:  { fill: '#3a3a3a', stroke: '#d4d4d4' },
};

const ARCHETYPE_FALLBACK_COLOR = {
  executor: 'blue',
  planner: 'teal',
  orchestrator: 'orange',
};

function nodeId(name) {
  return name.replace(/-/g, '_');
}

function nodeLabel(name) {
  return name;
}

function classDefName(color) {
  return `c_${color}`;
}

function colorFor(entry) {
  const c = entry.color;
  if (c && COLOR_FILLS[c]) return c;
  return ARCHETYPE_FALLBACK_COLOR[entry.archetype] ?? 'white';
}

function buildMermaid(executors, planners, orchestrators, allEntries) {
  const lines = ['flowchart TD'];

  // classDef per unique color used by any rendered agent.
  const usedColors = new Set();
  for (const entry of allEntries) usedColors.add(colorFor(entry));
  for (const color of usedColors) {
    const { fill, stroke } = COLOR_FILLS[color];
    lines.push(`  classDef ${classDefName(color)} fill:${fill},stroke:${stroke},color:#fff`);
  }
  lines.push('');

  // Node declarations.
  if (orchestrators.length > 0) {
    lines.push('  %% Orchestrator');
    for (const e of orchestrators) lines.push(`  ${nodeId(e.agent)}["${nodeLabel(e.agent)}"]`);
    lines.push('');
  }

  if (executors.length > 0) {
    lines.push('  %% Executors');
    for (const e of executors) lines.push(`  ${nodeId(e.agent)}["${nodeLabel(e.agent)}"]`);
    lines.push('');
  }

  if (planners.length > 0) {
    lines.push('  %% Planners');
    for (const e of planners) lines.push(`  ${nodeId(e.agent)}(["${nodeLabel(e.agent)}"])`);
    lines.push('');
  }

  // Edges: orchestrator → each executor.
  if (orchestrators.length > 0) {
    const orch = orchestrators[0].agent;
    lines.push('  %% Orchestrator dispatches to executors');
    for (const e of executors) lines.push(`  ${nodeId(orch)} -->|dispatch| ${nodeId(e.agent)}`);
    lines.push('');
  }

  // Executor chain: non-git-commit-push executors → git-commit-push (if present).
  const gitCommitPush = 'git-commit-push';
  const hasGitDeploy = executors.some((e) => e.agent === gitCommitPush);
  const chainTargets = executors.filter((e) => e.agent !== gitCommitPush);
  if (hasGitDeploy && chainTargets.length > 0) {
    lines.push('  %% Executors hand off to git-commit-push');
    for (const e of chainTargets) lines.push(`  ${nodeId(e.agent)} -->|done| ${nodeId(gitCommitPush)}`);
    lines.push('');
  }

  // Planners: side-channel "consults" arrow from orchestrator (or first executor).
  if (planners.length > 0) {
    const hub = orchestrators.length > 0 ? orchestrators[0].agent : executors[0]?.agent;
    if (hub) {
      lines.push('  %% Planners are side-channel consultants');
      for (const e of planners) lines.push(`  ${nodeId(hub)} -. consults .-> ${nodeId(e.agent)}`);
      lines.push('');
    }
  }

  // Per-agent class assignment.
  for (const e of allEntries) {
    lines.push(`  class ${nodeId(e.agent)} ${classDefName(colorFor(e))}`);
  }

  return lines.join('\n');
}

function buildMarkdown(projectName, mermaidBlock) {
  return `# Agent workflow — ${projectName}

This diagram shows the rendered agent set and their typical dispatch relationships.
Node fill colors come from each agent's \`color:\` frontmatter so multi-agent runs
are visually distinguishable. Executors are rectangular; planners are stadium-shaped; the orchestrator
is the dispatch hub.

\`\`\`mermaid
${mermaidBlock}
\`\`\`

> Generated by Hephaestus. Re-run \`hephaestus init\` to update after changing the agent set.
`;
}

/**
 * Writes workflow.md into targetDir showing the mermaid agent diagram.
 *
 * @param {string} targetDir — absolute path to the project being initialised
 * @param {object} projectContext — key/value map (must include project_name)
 * @param {Array<{ agent: string, outputPath: string, archetype: string, color?: string }>} renderedAgents
 * @param {Function} conflictHandler — async (absolutePath: string, content: string) => Promise<void>
 * @returns {Promise<{ written: string[], skipped: string[] }>}
 */
export async function write(targetDir, projectContext, renderedAgents, conflictHandler) {
  if (!renderedAgents || renderedAgents.length === 0) {
    console.log('workflow-diagram: no agents rendered — skipping workflow.md');
    return { written: [], skipped: [] };
  }

  // Deduplicate by agent name (multiple shells produce duplicate entries).
  const seen = new Set();
  const unique = [];
  for (const entry of renderedAgents) {
    if (!seen.has(entry.agent)) {
      seen.add(entry.agent);
      unique.push(entry);
    }
  }

  const executors     = unique.filter((e) => e.archetype === 'executor');
  const planners      = unique.filter((e) => e.archetype === 'planner');
  const orchestrators = unique.filter((e) => e.archetype === 'orchestrator');

  const mermaidBlock = buildMermaid(executors, planners, orchestrators, unique);
  const projectName  = projectContext.project_name ?? 'this project';
  const content      = buildMarkdown(projectName, mermaidBlock);

  const absolutePath = join(resolve(targetDir), 'workflow.md');
  await conflictHandler(absolutePath, content);

  return { written: [], skipped: [] };
}
